name: Sincronizar Inventario

on:
  schedule:
    # Se ejecuta automáticamente cada 30 minutos
    - cron: '*/30 * * * *'
  workflow_dispatch: # Te permite ejecutarlo manualmente con un botón

jobs:
  actualizar:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Descargar el repositorio
        uses: actions/checkout@v4

      - name: Crear carpeta de datos (si no existe)
        run: mkdir -p data

      - name: Descargar ERP (Power Automate)
        # Si el servidor falla, el parámetro -f detiene el proceso para no borrar tus datos guardados
        run: curl -sLf "https://defaultc9de65b0590045e8967debc553f353.81.environment.api.powerplatform.com:443/powerautomate/automations/direct/workflows/a652c02764724cdc81b3868ca8ad5df0/triggers/manual/paths/invoke?api-version=1&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=I3jYEqWHJW0it2AsocfVtb-4pLtR--_brJvTdCzB-cA" -o data/erp.json

      - name: Descargar Bodega PCO (Google Sheets)
        run: curl -sLf "https://docs.google.com/spreadsheets/d/1UuDzdH4DEjnedbSM7gvo4mxKF0YrPxJEz2z8JDSffAc/pub?gid=0&single=true&output=csv" -o data/pco.csv

      - name: Descargar Planes y Valores (Google Sheets)
        run: curl -sLf "https://docs.google.com/spreadsheets/d/e/2PACX-1vRvOH3xHFkBQ-BzvfRUi5rdXDT9pZOlgUXgvPFEpnyxphL5d282gGaEwm1_HggiW3iumBmhFTdEVQcr/pub?gid=1192465732&single=true&output=csv" -o data/extra.csv

      - name: Guardar cambios en GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*
          git diff --quiet && git diff --staged --quiet || (git commit -m "🤖 Update: Inventario sincronizado" && git push)
